services:
  application:
    image: ${ORO_IMAGE}:${ORO_IMAGE_TAG}
    command: tail -f /dev/null
    env_file: .env
    depends_on:
      web:
        condition: service_started
      consumer:
        condition: service_started
      cron:
        condition: service_started
    networks:
      - oro-network
