x-depends_on: &default-depends_on
  "db":
    condition: service_healthy
  "mail":
    condition: service_started

include:
  - application.yaml
  - web.yaml
  - db.yaml
  - consumer.yaml

services:
  php-fpm-app:
    image: ${ORO_IMAGE}:${ORO_IMAGE_TAG}
    command: php-fpm
    user: ${ORO_USER_RUNTIME:-www-data}
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck"]
      interval: 5s
      timeout: 30s
      start_period: 120s
    restart: unless-stopped
    depends_on:
      <<: *default-depends_on
      init:
        condition: service_completed_successfully
    volumes:
      - cache:/var/www/oro/var/cache
      - public:/var/www/oro/public
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data
      - run_php_fpm:/run/php-fpm

  ws:
    image: ${ORO_IMAGE}:${ORO_IMAGE_TAG}
    command: websocket
    env_file: .env
    restart: unless-stopped
    user: ${ORO_USER_RUNTIME:-www-data}
    init: true
    depends_on:
      php-fpm-app:
        condition: service_healthy
    volumes:
      - cache:/var/www/oro/var/cache
      - public:/var/www/oro/public
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  cron:
    image: ${ORO_IMAGE}:${ORO_IMAGE_TAG}
    command: cron
    env_file: .env
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1024
        hard: 1048576
    depends_on:
      php-fpm-app:
        condition: service_healthy
    volumes:
      - cache:/var/www/oro/var/cache
      - public:/var/www/oro/public
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  install:
    image: ${ORO_IMAGE}:${ORO_IMAGE_TAG}
    command: console oro:install --no-interaction --timeout=3600 --user-name="$ORO_USER_NAME" --user-email="$ORO_USER_EMAIL" --user-firstname="$ORO_USER_FIRSTNAME" --user-lastname="$ORO_USER_LASTNAME" --user-password="$ORO_USER_PASSWORD" --sample-data="$ORO_SAMPLE_DATA" --organization-name="$ORO_ORGANIZATION_NAME" --language=$ORO_LANGUAGE --formatting-code=$ORO_FORMATTING_CODE --application-url="$ORO_APP_PROTOCOL://$ORO_APP_DOMAIN" $ORO_INSTALL_OPTIONS
    user: $ORO_USER_RUNTIME
    env_file: .env
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public:/var/www/oro/public
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  restore: &restore
    image: ${ORO_IMAGE_INIT}${ORO_LANGUAGE_SUFFIX-}:${ORO_IMAGE_TAG}
    command: restore
    user: $ORO_USER_RUNTIME
    env_file: .env
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public:/var/www/oro/public
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  init:
    image: ${ORO_IMAGE}:${ORO_IMAGE_TAG}
    command: init
    env_file: .env
    volumes:
      - etc_nginx:/etc/nginx
      - run_php_fpm:/run/php-fpm
      - public:/var/www/oro/public

  mail:
    image: mailhog/mailhog
    hostname: mail
    environment:
      MH_UI_WEB_PATH: mailcatcher
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog/maildir
    restart: unless-stopped

networks:
  oro-network:
    driver: bridge

volumes:
  cache:
  public_storage:
  private_storage:
  etc_nginx:
  run_php_fpm:
  public:
